[tool.poetry]
name = "python_condition_generate"
version = "0.1.0"
description = ""
authors = ["Phakawat Fongchai <phakawatfong@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"